# Generated by Django 2.1.7 on 2019-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contractor',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('contactnumber', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.PositiveIntegerField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
