# Generated by Django 2.1.7 on 2019-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
