# Generated by Django 2.1.7 on 2019-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190221_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.CharField(max_length=60),
        ),
    ]
