# Generated by Django 2.1.7 on 2019-04-10 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contractor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='labour',
            fields=[
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')])),
                ('contactnumber', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')])),
                ('skills', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')])),
                ('gender', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')])),
                ('address', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'only alphaumeric allowed')])),
                ('city', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')])),
                ('state', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')])),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')])),
            ],
        ),
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'only alphaumeric allowed')]),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='city',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contactnumber',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')]),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='gender',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')]),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='state',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')]),
        ),
    ]
