# Generated by Django 2.1.7 on 2019-04-18 13:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20190410_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')])),
                ('gender', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')])),
                ('address', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'only alphaumeric allowed')])),
                ('city', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')])),
                ('state', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed.')])),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
