# Generated by Django 2.1.7 on 2019-04-21 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'only numbers allowed')]),
        ),
    ]
