# Generated by Django 2.1.7 on 2019-04-22 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190421_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'only alphaumeric allowed')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'only alphabets are allowed.')]),
        ),
    ]
